site_name: kentokit
site_description: Add your description here
repo_name: vienneraphael/kentokit
repo_url: https://github.com/vienneraphael/kentokit
site_dir: docs-site
strict: true

theme:
  name: material
  custom_dir: docs/overrides
  pygments_style: tango
  pygments_style_dark: monokai
  font:
    text: IBM Plex Sans
    code: JetBrains Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.tooltips
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - toc.follow

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vienneraphael/kentokit
      name: GitHub

plugins:
  - search
  - mkdocstrings:
      default_handler: python

markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.snippets:
      base_path:
        - .
        - docs
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      pygments_lang_class: true
  - toc:
      permalink: false

extra_css:
  - assets/stylesheets/extra.css
extra_javascript:
  - assets/javascripts/bash-command-highlight.js

nav:
  - kentokit: index.md
  - Architecture:
      - API: architecture/api.md
      - Providers: architecture/providers.md
  - Token Counting: token-counting.md
  - Provider Input Recap: provider-input-recap.md
