name: Publish to PyPI
permissions:
  id-token: write
  contents: read

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish-env

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Build package
        run: uv build

      - name: Publish to PyPI
        run: uv publish
